name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0
    - name: Build
      run: dotnet build -c Release src/WindyCliffs.Clock.sln
    - name: Test
      run: dotnet test -c Release --no-build src/WindyCliffs.Clock.sln
    - name: Pack nugets
      run: dotnet pack -c Release --no-build src/WindyCliffs.Clock/WindyCliffs.Clock.csproj --output out/
    - name: Push to NuGet
      run: dotnet nuget push out\*.nupkg --api-key ${{secrets.nuget_publish}} --source https://api.nuget.org/v3/index.json
